"""
Small, hand-curated pieces of app content that are NOT generated by the LLM.

These are short category blurbs and event orderings used by the Stories and
Timeline pages. They exist so those pages can render instantly without an LLM
call, and so the timeline never risks inventing a sequence of events - it's
just static data describing the sample documents shipped in data/.

If you add real source material to data/, update these to match, or wire the
timeline/story blurbs up to your own indexed content instead.
"""

# Short, general descriptions of each tradition. These are not claims about
# any specific character or event - just labels shown at the top of each
# story card. The actual characters/sections/topics shown alongside them on
# the Stories page come from rag/catalog.py, which reads real indexed metadata.
STORY_INFO = {
    "Ramayana": (
        "The story of Prince Rama of Ayodhya - his marriage to Sita, his exile, "
        "her abduction by Ravana, and the war fought to bring her home."
    ),
    "Mahabharata": (
        "The story of the rivalry between the Pandavas and the Kauravas, "
        "culminating in the great war at Kurukshetra."
    ),
    "Bhagavad Gita": (
        "Krishna's counsel to Arjuna on the Kurukshetra battlefield, on duty, "
        "action, and the nature of the self."
    ),
    "Puranas": (
        "Traditional stories about the gods - their origins, families, and "
        "avatars - collected in the Puranic texts."
    ),
    "General": (
        "Background and overview material that spans more than one "
        "mythological tradition."
    ),
}

# Traditional narrative order of major events per epic, as depicted in the
# sample documents. These are NOT historical dates - just the sequence the
# story unfolds in, for the Timeline page.
TIMELINE = {
    "Ramayana": [
        "Rama's birth in Ayodhya",
        "Sita's swayamvara and marriage to Rama",
        "Rama's exile to the forest",
        "Sita's abduction by Ravana",
        "Hanuman's journey to Lanka in search of Sita",
        "The war in Lanka",
        "Rama's return and coronation in Ayodhya",
    ],
    "Mahabharata": [
        "Birth of Karna, and of the Pandavas and Kauravas",
        "Rivalry between the Pandavas and Kauravas grows",
        "The game of dice and the Pandavas' exile",
        "Krishna's counsel to Arjuna before the war (Bhagavad Gita)",
        "The Kurukshetra war begins",
        "Death of Abhimanyu in the Chakravyuha",
        "End of the Kurukshetra war",
    ],
}
